import matter from "gray-matter";

// This interface should match the one in PodcastPage.tsx and the frontmatter
// generated by the podcast-generator.yml workflow.
export interface PodcastEpisode {
  slug: string;
  title: string;
  date: string;
  excerpt: string;
  audio_url: string;
  content: string;
}

// This uses Vite's special `import.meta.glob` feature to find all .md files
// in the /content/podcasts/ directory at build time.
const podcastImports = import.meta.glob("/content/podcasts/*.md", {
  query: "?raw",
  import: "default",
  eager: true,
});

export function getAllPodcastEpisodes(): PodcastEpisode[] {
  const episodes = Object.entries(podcastImports).map(
    ([filepath, rawContent]) => {
      const { data, content } = matter(rawContent);

      // The slug is derived from the frontmatter, falling back to the filename.
      const slug = data.slug || filepath.split("/").pop()!.replace(".md", "");

      return { ...data, slug, content } as PodcastEpisode;
    }
  );

  // Sort episodes by date, with the newest first.
  return episodes.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}