import React from 'react';
import { renderToString } from 'react-dom/server';
import { StaticRouter } from 'react-router-dom/server';
// @ts-ignore: Bypass TS check for Node.js CommonJS compatibility
import pkg from 'react-helmet-async';
import App from './App';

// Destructure HelmetProvider from the default import to satisfy Node.js
const { HelmetProvider } = pkg;

export function render(url: string) {
  const helmetContext = {} as any;
  
  const html = renderToString(
    <React.StrictMode>
      <HelmetProvider context={helmetContext}>
        <StaticRouter location={url}>
          <App />
        </StaticRouter>
      </HelmetProvider>
    </React.StrictMode>
  );
  
  const { helmet } = helmetContext;
  
  // Extract all the tags generated by your ArticlePage helmet
  // Added optional chaining just in case a page has no helmet data
  const head = `
    ${helmet?.title?.toString() || ""}
    ${helmet?.meta?.toString() || ""}
    ${helmet?.link?.toString() || ""}
  `;
  
  return { html, head };
}